In [13]:
import torch 
import torchvision.datasets as datasets
from torch.utils.data import DataLoader,WeightedRandomSampler
from torchvision.transforms import transforms
import torch.nn as nn


In [47]:
def get_loader(roo_dir,batch_size):
    mytransforms=transforms.Compose([transforms.Resize((500,500)),
                                    transforms.ToTensor()])
    dataset = datasets.ImageFolder(roo_dir,transform=mytransforms)
    classlabel = [1,50]
    sample_weight=[0]*len(dataset)
    print(dataset)
    for idx,(data,label) in enumerate(dataset):
        classweight=classlabel[label]
        sample_weight[idx]=classweight
    sampler = WeightedRandomSampler(sample_weight,num_samples=len(dataset),replacement=True)
    loader = DataLoader(dataset,batch_size=batch_size,sampler=sampler)
    return loader
def main():
    loader = get_loader('class/',2)
    for (x,y) in loader:
        print(y)

In [48]:
if __name__=="__main__":
    main()

Dataset ImageFolder
    Number of datapoints: 7
    Root location: class/
    StandardTransform
Transform: Compose(
               Resize(size=(500, 500), interpolation=PIL.Image.BILINEAR)
               ToTensor()
           )
tensor([1, 0])
tensor([1, 1])
tensor([1, 1])
tensor([0])
